(define (problem moving_balls)
   (:domain robot_two_grippers)
   (:objects rooma roomb roomc roomd roome roomf ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 left right)
   (:init (room rooma)
          (room roomb)
          (room roomc)
          (room roomd)
          (room roome)
          (room roomf)
          (ball ball8)
          (ball ball7)
          (ball ball6)
          (ball ball5)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at_robby rooma)
          (free left)
          (free right)
          (corridor rooma roomb)
          (corridor roomb rooma)
          (corridor roomb roomc)
          (corridor roomc roomb)
          (corridor rooma roomd)
          (corridor roomd rooma)
          (corridor roomd roome)
          (corridor roome roomd)
          (corridor roome roomf)
          (corridor roomf roome)
          (here ball8 rooma)
          (here ball7 roomb)
          (here ball6 rooma)
          (here ball5 roomd)
          (here ball4 roome)
          (here ball3 rooma)
          (here ball2 rooma)
          (here ball1 roomf)
          (gripper left)
          (gripper right))
   (:goal (and 
                (here ball8 roomc)
                (here ball7 roomc)
                (here ball6 roomc)
                (here ball5 roomc)
                (here ball4 roomf)
                (here ball3 roomf)
                (here ball2 roomf)
                (here ball1 roomf)
                (used left)
                (used right))))