(define (problem moving_balls)
   (:domain robot-two-grippers-maze)
   (:objects rooma roomb roomc roomd roome roomf ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 left right)
   (:init 
       (room rooma)
       (room roomb)
       (room roomc)
       (room roomd)
       (room roome)
       (room roomf)
       (ball ball8)
       (ball ball7)
       (ball ball6)
       (ball ball5)
       (ball ball4)
       (ball ball3)
       (ball ball2)
       (ball ball1)
       (at-robby rooma)
       (free left)
       (free right)
       (corridor rooma roomb)
       (corridor roomb rooma)
       (corridor roomb roomc)
       (corridor roomc roomb)
       (corridor rooma roomd)
       (corridor roomd rooma)
       (corridor roomd roome)
       (corridor roome roomd)
       (corridor roome roomf)
       (corridor roomf roome)
       (at ball8 rooma)
       (at ball7 roomb)
       (at ball6 rooma)
       (at ball5 roomd)
       (at ball4 roome)
       (at ball3 rooma)
       (at ball2 rooma)
       (at ball1 roomf)
       (gripper left)
       (gripper right)
       (goal-location ball8 roomc)
       (goal-location ball6 roomc)
       (goal-location ball7 roomc)
       (goal-location ball5 roomc)
       (goal-location ball2 roomf)
       (goal-location ball3 roomf)
       (goal-location ball4 roomf)
       (goal-location ball1 roomf)          )
   (:goal (and 
                (at ball8 roomc)
                (at ball7 roomc)
                (at ball6 roomc)
                (at ball5 roomc)
                (at ball4 roomf)
                (at ball3 roomf)
                (at ball2 roomf)
                (at ball1 roomf)
                (used left)
                (used right))))