(define 
    (problem BLOCKS-10-0)
    (:domain BLOCKS)
    (:objects A B C D E F G H I J - blocks
              left-hand right-hand - hands)
    (:init
        (clear C)
        (clear F)
        (ontable I)
        (ontable F)
        (on C E)
        (on E J)
        (on J B)
        (on B G)
        (on G H)
        (on H A)
        (on A D)
        (on D I)
        (handempty left-hand)
        (handempty right-hand)
    )
    (:goal 
        (AND
            (on A B)
            (on B C)
            (on C D)
            (on D E)
            (on E F)
            (on F G)
            (on G H)
            (on H I)
            (on I J)
        )
    )
)