(define 
    (problem BLOCKS-10-0)
    (:domain BLOCKS)
    (:objects D A H G B J E I F C)
    (:init
        (clear C)
        (clear F)
        (ontable I)
        (ontable F)
        (On C E)
        (On E J)
        (On J B)
        (On B G)
        (On G H)
        (On H A)
        (On A D)
        (On D I)
        (handempty)
    )
    (:goal 
        (AND
            (On D C)
            (On C F)
            (On F J)
            (On J E)
            (On E H)
            (On H B)
            (On B A)
            (On A G)
            (On G I)
        )
    )
)